<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKYCipwv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKYCipwv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKYCipwv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKYCipwv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKYCipwv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KYCipwv',
    'container.build_id' => '0eb0506a',
    'container.build_time' => 1606233358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKYCipwv');
